apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-test2
spec:
  destination:
    namespace: test2
    server: https://kubernetes.default.svc
  source:
    path: dev
    repoURL: https://github.com/lahcenaghouar/argocd-test2.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
